services:
  giftflow:
    build:
      context: .
    container_name: giftflow
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "8080:3000"
    environment:
      - DEFAULT_LANG=en
