services:
  giftflow:
    image: ghcr.io/garnajee/giftflow:latest
    container_name: giftflow
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "7006:3000"
    environment:
      - DEFAULT_LANG=en
